### ISSUE TITLE
error when generating bindings for linux on raspberry pi 3

### ISSUE THREAD

**Issue by stephanschulz** [danomatika/swig-openframeworks#11]
i am trying to make new swig bindings for ofxPython.
it worked will for of 0.9.8 on OS X but not on linux on my pi3.

i am using the .generatebindings.sh from ofxPython
https://github.com/antimodular/ofxPython/blob/master/generatebindings.sh
i changed the word desktop to linuxarm as per your readme file.

but i get make: *** No rule to make target 'linuxarm'. Stop

would you know what i am doing wrong?

thanks.

**Comment by danomatika** [comment]
Looks like the swig-of submodule in ofxPython is 2 years old, probably before the linuxarm target was added. Update to the current version.

Also, I'd suggest updating the generatebindings.sh script to generate both desktop and linuxarm bindings to subdirectories and then only build the correct source files based on the platform. This is what ofxLua does, see https://github.com/danomatika/ofxLua/blob/master/scripts/generate_bindings.sh and https://github.com/danomatika/ofxLua/blob/master/addon_config.mk.

**Comment by stephanschulz** [comment]
wow thanks for your super fast reply.

i have forked the original addon, downloaded your current swig master, and got it all to work for of 0.9.8.  see my OF0.9.8 branch

but linux was still not working. but i see now that in addon_config.mk armv6+7 was empty.

so i will try these changes:
https://github.com/antimodular/ofxPython/blob/OF0.9.8/generatebindings.sh
https://github.com/antimodular/ofxPython/blob/OF0.9.8/addon_config.mk
do you think this will work?

this is all new to me. i am learning as i go. 

thanks.

**Comment by danomatika** [comment]
In the addon_config.mk:

* you also need to exclude the linuxarm sources for the desktop bindings
* you don't need "src/bindings/ios/%" since that project is not building for iOS

For the generatebindings script:

* as it is, it looks like running make twice overwrites the first openframeworks.py on the second run, you'll need to probably set a different name for the linuxarm bindings or, better yet, put it in a subfolder as I do with ofxLua

**Comment by danomatika** [comment]
Also, open an issue to update ofxPython on the ofxPython repo. The rest are details with that project and not specific to the swig bindings.
