### ISSUE TITLE
support for ofMaterialSettings

### ISSUE THREAD

**Issue by coolvision** [danomatika/swig-openframeworks#22]
are there any problems with adding ofMaterialSettings?
would it be hard to for some reason, or is it just a matter of uncommenting and testing?

**Comment by danomatika** [comment]
>or is it just a matter of uncommenting and testing?

Bingo. See 14d0b4d

**Comment by coolvision** [comment]
Wow thanks this was fast :)
Tested, and it works

**Comment by danomatika** [comment]
There may be a couple more settings structs like this which are ignored. I went through the OF 0.10 API quickly and ignored what I thought were edge cases for now as the amount of bindings is already so large.

BTW: Which scripting language do you generate bindings for?

**Comment by coolvision** [comment]
Just using ofxLua

**Comment by danomatika** [comment]
Ok, cool. I sometimes cannot gauge how much interest there is in this project or the lua bindings. It seems most people want Javascript... :P
